import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import About from '../components/about/About'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center bg-slate-100 dark:bg-[#05011a]">
        <About/>
      </main>
    </>
  );
};

export default Home;
