import { type NextPage } from "next";
import Head from "next/head";
import About from '../components/about/About'
import Carousel from "../components/carousel/Carousel";
import { projects } from '../utils/projects'
import Project from '../components/projects/Project'
import Contact from '../components/contact/Contact'

const Home: NextPage = () => {
  const slides = projects.map(project=> <Project key={project.title} project={project}/>)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col md:items-center font-serif bg-slate-300 dark:bg-[#05011a]">
        <h1 className='dark:text-slate-300 text-4xl mt-8'>Hello There, My Name Is</h1>
        <About/>
        <h1 className='mt-8 dark:text-slate-300 text-4xl'>My Projects</h1>
        <Carousel>
          {slides}
        </Carousel>
        <h1 className='mt-8 text-slate-300 text-4xl'>How To Reach Me</h1>
        <Contact/>
      </main>
    </>
  );
};

export default Home;
